name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # ვასუფთავებთ ადგილს დისკზე
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-dev
          pip3 install --user --upgrade Cython==0.29.33 virtualenv buildozer

      - name: Build with Buildozer
        run: |
          rm -rf .buildozer
          # ვიყენებთ მხოლოდ 1 ბირთვს, რომ RAM არ გადაიტვირთოს
          buildozer -v android debug
