name: Build Android APK
on:
  push:
    branches: [ "main", "master" ] # გაეშვება როცა კოდს ატვირთავთ main ან master ბრენჩზე
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # ეს არის სპეციალური ექშენი, რომელიც ყველაზე სტაბილურად აშენებს Kivy/KivyMD აპლიკაციებს
      - name: Build with Buildozer
        uses: ArtemSashko/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_read_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RSS-Control-Center-${{ steps.get-date.outputs.date }}
          path: bin/*.apk
